// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { exec } from 'node:child_process'
import { readFile, writeFile } from 'node:fs/promises'
import { promisify } from 'node:util'
import { error, getRepoRoot, success, warn } from './lib/utils.js'

const ex = promisify(exec)
const repoRoot = getRepoRoot()

const SCHEMA_PATH = `${repoRoot}/docs/dapp-building/wallet-gateway/configuration/schema.md`

async function main() {
    // first build
    await ex(`yarn nx build @canton-network/wallet-gateway-remote`, {
        cwd: repoRoot,
    })

    const existing = await readFile(SCHEMA_PATH, { encoding: 'utf-8' })

    const { stdout } = await ex(
        `yarn workspace @canton-network/wallet-gateway-remote run tsx ./src/index.ts --config-schema`
    )

    if (stdout) {
        const contents = `
# JSON Schema for Wallet Gateway Configuration File

The contents of this file was generated by the following command:

\`\`\`shell
npx @canton-network/wallet-gateway-remote@latest --config-schema
\`\`\`

\`\`\`json
${stdout}
\`\`\`
        `

        // compare contents without worrying about formatting/spacing
        if (existing.replace(/\s/g, '') !== contents.replace(/\s/g, '')) {
            console.warn(
                warn(
                    'Contents were outdated. If you see this in CI, run `yarn docs:update-wg-config` and commit the results'
                )
            )
            // set exit code to non-zero, so that CI will fail if the docs are out-of-date
            process.exitCode = 1
        }

        await writeFile(SCHEMA_PATH, contents)
        console.log(success('Wrote JSON Schema to docs file.'))
    } else {
        console.error(error('Command to generate JSON Schema failed.'))
    }
}

main()
