// Code generated by @open-rpc/generator DO NOT EDIT.
import _ from 'lodash'

import { RequestArgs, RequestPayload } from '@canton-network/core-types'
import { RpcTransport } from '@canton-network/core-rpc-transport'

/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 *
 * The unique identifier of the command associated with the transaction.
 *
 */
export type CommandId = string
type AlwaysTrue = any
/**
 *
 * Structure representing JS commands for transaction execution
 *
 */
export interface JsCommands {
    [key: string]: any
}
/**
 *
 * The party that signed the transaction.
 *
 */
export type Party = string
/**
 *
 * Set of parties on whose behalf the command should be executed, if submitted. If not set, the primary wallet's party is used.
 *
 */
export type ActAs = Party[]
/**
 *
 * Set of parties that should be granted read access to the command, if submitted. If not set, no additional read parties are granted.
 *
 */
export type ReadAs = Party[]
/**
 *
 * The template identifier of the disclosed contract.
 *
 */
export type TemplateId = string
/**
 *
 * The unique identifier of the disclosed contract.
 *
 */
export type ContractId = string
/**
 *
 * The blob data of the created event for the disclosed contract.
 *
 */
export type CreatedEventBlob = string
/**
 *
 * If not set, a suitable synchronizer that this node is connected to will be chosen.
 *
 */
export type SynchronizerId = string
/**
 *
 * Structure representing a disclosed contract for transaction execution
 *
 */
export interface DisclosedContract {
    templateId?: TemplateId
    contractId?: ContractId
    createdEventBlob: CreatedEventBlob
    synchronizerId?: SynchronizerId
}
/**
 *
 * List of contract IDs to be disclosed with the command.
 *
 */
export type DisclosedContracts = DisclosedContract[]
export type PackageId = string
/**
 *
 * The package-id selection preference of the client for resolving package names and interface instances in command submission and interpretation
 *
 */
export type PackageIdSelectionPreference = PackageId[]
/**
 *
 * The message to sign.
 *
 */
export type Message = string
export type RequestMethod = 'GET' | 'POST' | 'PUT' | 'DELETE'
export type Resource = string
export type Body = string
/**
 *
 * The unique identifier of the Provider.
 *
 */
export type ProviderId = string
/**
 *
 * The version of the Provider.
 *
 */
export type Version = string
/**
 *
 * The type of client that implements the Provider.
 *
 */
export type ProviderType = 'browser' | 'desktop' | 'mobile' | 'remote'
/**
 *
 * The URL of the Wallet Provider.
 *
 */
export type Url = string
/**
 *
 * A URL that points to a user interface.
 *
 */
export type UserUrl = string
/**
 *
 * Represents a Provider.
 *
 */
export interface Provider {
    id: ProviderId
    version?: Version
    providerType?: ProviderType
    url?: Url
    userUrl?: UserUrl
}
/**
 *
 * Whether or not the user is authenticated with the Wallet.
 *
 */
export type IsConnected = boolean
/**
 *
 * Reason for the wallet state, e.g., 'no signing provider matched'.
 *
 */
export type Reason = string
/**
 *
 * Whether or not a connection to a network is established.
 *
 */
export type IsNetworkConnected = boolean
/**
 *
 * If not connected to a network, the reason why.
 *
 */
export type NetworkReason = string
export interface ConnectResult {
    isConnected: IsConnected
    reason?: Reason
    isNetworkConnected: IsNetworkConnected
    networkReason?: NetworkReason
    userUrl?: UserUrl
}
/**
 *
 * The network ID the wallet corresponds to.
 *
 */
export type NetworkId = string
/**
 *
 * The base URL of the ledger API.
 *
 */
export type LedgerApiUrl = string
/**
 *
 * JWT authentication token.
 *
 */
export type AccessToken = string
/**
 *
 * Network information, if connected to a network.
 *
 */
export interface Network {
    networkId: NetworkId
    ledgerApi?: LedgerApiUrl
    accessToken?: AccessToken
}
/**
 *
 * The user identifier.
 *
 */
export type UserId = string
/**
 *
 * Session information, if authenticated.
 *
 */
export interface Session {
    accessToken: AccessToken
    userId: UserId
}
/**
 *
 * The signature of the transaction.
 *
 */
export type Signature = string
export type Response = string
/**
 *
 * Set as primary wallet for dApp usage.
 *
 */
export type Primary = boolean
/**
 *
 * The party ID corresponding to the wallet.
 *
 */
export type PartyId = string
/**
 *
 * The status of the wallet.
 *
 */
export type WalletStatus = 'initialized' | 'allocated'
/**
 *
 * The party hint and name of the wallet.
 *
 */
export type Hint = string
/**
 *
 * The public key of the party.
 *
 */
export type PublicKey = string
/**
 *
 * The namespace of the party.
 *
 */
export type Namespace = string
/**
 *
 * The signing provider ID the wallet corresponds to.
 *
 */
export type SigningProviderId = string
/**
 *
 * Unique identifier of the signed transaction given by the Signing Provider. This may not be the same as the internal txId given by the Wallet Gateway.
 *
 */
export type ExternalTxId = string
/**
 *
 * The topology transactions
 *
 */
export type TopologyTransactions = string
/**
 *
 * Whether the wallet is disabled. Wallets are disabled when no signing provider matches the party's namespace during sync. Disabled wallets use participant as the default signing provider.
 *
 */
export type Disabled = boolean
/**
 *
 * Structure representing a wallet
 *
 */
export interface Wallet {
    primary: Primary
    partyId: PartyId
    status: WalletStatus
    hint: Hint
    publicKey: PublicKey
    namespace: Namespace
    networkId: NetworkId
    signingProviderId: SigningProviderId
    externalTxId?: ExternalTxId
    topologyTransactions?: TopologyTransactions
    disabled?: Disabled
    reason?: Reason
}
/**
 *
 * The status of the transaction.
 *
 */
export type StatusPending = 'pending'
/**
 *
 * Event emitted when a transaction is pending.
 *
 */
export interface TxChangedPendingEvent {
    status: StatusPending
    commandId: CommandId
}
/**
 *
 * The status of the transaction.
 *
 */
export type StatusSigned = 'signed'
/**
 *
 * The identifier of the provider that signed the transaction.
 *
 */
export type SignedBy = string
/**
 *
 * Payload for the TxChangedSignedEvent.
 *
 */
export interface TxChangedSignedPayload {
    signature: Signature
    signedBy: SignedBy
    party: Party
}
/**
 *
 * Event emitted when a transaction has been signed.
 *
 */
export interface TxChangedSignedEvent {
    status: StatusSigned
    commandId: CommandId
    payload: TxChangedSignedPayload
}
/**
 *
 * The status of the transaction.
 *
 */
export type StatusExecuted = 'executed'
/**
 *
 * The update ID corresponding to the transaction.
 *
 */
export type UpdateId = string
export type CompletionOffset = number
/**
 *
 * Payload for the TxChangedExecutedEvent.
 *
 */
export interface TxChangedExecutedPayload {
    updateId: UpdateId
    completionOffset: CompletionOffset
}
/**
 *
 * Event emitted when a transaction is executed against the participant.
 *
 */
export interface TxChangedExecutedEvent {
    status: StatusExecuted
    commandId: CommandId
    payload: TxChangedExecutedPayload
}
/**
 *
 * The status of the transaction.
 *
 */
export type StatusFailed = 'failed'
/**
 *
 * Event emitted when a transaction has failed.
 *
 */
export interface TxChangedFailedEvent {
    status: StatusFailed
    commandId: CommandId
}
/**
 *
 * Structure representing the request for prepare and execute calls
 *
 */
export interface PrepareExecuteParams {
    commandId?: CommandId
    commands: JsCommands
    actAs?: ActAs
    readAs?: ReadAs
    disclosedContracts?: DisclosedContracts
    synchronizerId?: SynchronizerId
    packageIdSelectionPreference?: PackageIdSelectionPreference
}
/**
 *
 * Request to sign a message.
 *
 */
export interface SignMessageParams {
    message: Message
}
/**
 *
 * Ledger API request structure
 *
 */
export interface LedgerApiParams {
    requestMethod: RequestMethod
    resource: Resource
    body?: Body
}
export interface StatusEvent {
    provider: Provider
    connection: ConnectResult
    network?: Network
    session?: Session
}
/**
 *
 * Represents a null value, used in responses where no data is returned.
 *
 */
export type Null = null
export interface PrepareExecuteResult {
    userUrl: UserUrl
}
/**
 *
 * Result of signing a message.
 *
 */
export interface SignMessageResult {
    signature: Signature
}
/**
 *
 * Ledger Api configuration options
 *
 */
export interface LedgerApiResult {
    response: Response
}
/**
 *
 * Event emitted when the user's accounts change.
 *
 */
export type AccountsChangedEvent = Wallet[]
/**
 *
 * An array of accounts that the user has authorized the dapp to access..
 *
 */
export type ListAccountsResult = Wallet[]
/**
 *
 * Event emitted when a transaction changes.
 *
 */
export type TxChangedEvent =
    | TxChangedPendingEvent
    | TxChangedSignedEvent
    | TxChangedExecutedEvent
    | TxChangedFailedEvent
/**
 *
 * Generated! Represents an alias to any of the provided schemas
 *
 */

export type Status = () => Promise<StatusEvent>
export type Connect = () => Promise<ConnectResult>
export type Disconnect = () => Promise<Null>
export type GetActiveNetwork = () => Promise<Network>
export type PrepareExecute = (
    params: PrepareExecuteParams
) => Promise<PrepareExecuteResult>
export type SignMessage = (
    params: SignMessageParams
) => Promise<SignMessageResult>
export type LedgerApi = (params: LedgerApiParams) => Promise<LedgerApiResult>
export type Connected = () => Promise<StatusEvent>
export type OnStatusChanged = () => Promise<StatusEvent>
export type AccountsChanged = () => Promise<AccountsChangedEvent>
export type GetPrimaryAccount = () => Promise<Wallet>
export type ListAccounts = () => Promise<ListAccountsResult>
export type TxChanged = () => Promise<TxChangedEvent>
/* eslint-enable @typescript-eslint/no-unused-vars */

type Params<T> = T extends (...args: infer A) => any
    ? A extends []
        ? never
        : A[0]
    : never
type Result<T> = T extends (...args: any[]) => Promise<infer R> ? R : never

export type RpcTypes = {
    status: {
        params: Params<Status>
        result: Result<Status>
    }

    connect: {
        params: Params<Connect>
        result: Result<Connect>
    }

    disconnect: {
        params: Params<Disconnect>
        result: Result<Disconnect>
    }

    getActiveNetwork: {
        params: Params<GetActiveNetwork>
        result: Result<GetActiveNetwork>
    }

    prepareExecute: {
        params: Params<PrepareExecute>
        result: Result<PrepareExecute>
    }

    signMessage: {
        params: Params<SignMessage>
        result: Result<SignMessage>
    }

    ledgerApi: {
        params: Params<LedgerApi>
        result: Result<LedgerApi>
    }

    connected: {
        params: Params<Connected>
        result: Result<Connected>
    }

    onStatusChanged: {
        params: Params<OnStatusChanged>
        result: Result<OnStatusChanged>
    }

    accountsChanged: {
        params: Params<AccountsChanged>
        result: Result<AccountsChanged>
    }

    getPrimaryAccount: {
        params: Params<GetPrimaryAccount>
        result: Result<GetPrimaryAccount>
    }

    listAccounts: {
        params: Params<ListAccounts>
        result: Result<ListAccounts>
    }

    txChanged: {
        params: Params<TxChanged>
        result: Result<TxChanged>
    }
}

export class SpliceWalletJSONRPCRemoteDAppAPI {
    public transport: RpcTransport

    constructor(transport: RpcTransport) {
        this.transport = transport
    }

    public async request<M extends keyof RpcTypes>(
        args: RequestArgs<RpcTypes, M>
    ): Promise<RpcTypes[M]['result']> {
        const response = await this.transport.submit(args as RequestPayload)

        if ('error' in response) {
            throw new Error(
                'RPC error: ' +
                    response.error.code +
                    ' - ' +
                    response.error.message
            )
        } else {
            return response.result as RpcTypes[M]['result']
        }
    }
}
export default SpliceWalletJSONRPCRemoteDAppAPI
